- ros_topic_name: "/robot_scan/cmd_vel"
  gz_topic_name: "/model/robot_scan/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/robot_scan/odometry"
  gz_topic_name: "/model/robot_scan/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/robot_scan/scan"
  gz_topic_name: "/model/robot_scan/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/model/robot_scan/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS
  qos:
    publisher:
      history: keep_last
      history_depth: 20
      reliability: reliable
      durability: volatile

- ros_topic_name: "/tf_static"
  gz_topic_name: "/model/robot_scan/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS
  qos:
    publisher:
      history: keep_last
      history_depth: 1
      reliability: reliable
      durability: transient_local

# 添加以下桥接配置，用于控制无人小车位置
- ros_topic_name: "/robot_scan/pose"
  gz_topic_name: "/model/robot_scan/pose_cmd"
  ros_type_name: "geometry_msgs/msg/Pose"
  gz_type_name: "ignition.msgs.Pose"
  direction: ROS_TO_GZ
  qos:
    publisher:
      history: keep_last
      history_depth: 1
      reliability: reliable
      durability: volatile

- ros_topic_name: "/quadcopter/cmd_vel"
  gz_topic_name: "/quadcopter/command/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/quadcopter/odometry"
  gz_topic_name: "/model/quadcopter/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/quadcopter/altimeter"
  gz_topic_name: "/model/quadcopter/altimeter"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/model/quadcopter/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS
  qos:
    publisher:
      history: keep_last
      history_depth: 20
      reliability: reliable
      durability: volatile

- ros_topic_name: "/tf_static"
  gz_topic_name: "/model/quadcopter/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS
  qos:
    publisher:
      history: keep_last
      history_depth: 1
      reliability: reliable
      durability: transient_local

- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

# rgbd camera
- ros_topic_name: "/quadcopter/rgbd_camera/image_raw"
  gz_topic_name: "/quadcopter/rgbd_camera/image_raw/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS
  qos:
    publisher:
      history: keep_last
      history_depth: 1
      reliability: best_effort
      durability: volatile
      deadline:
        sec: 0
        nsec: 100000000  # 10Hz
      lifespan:
        sec: 0
        nsec: 100000000  # 10Hz

- ros_topic_name: "/quadcopter/rgbd_camera/camera_info"
  gz_topic_name: "/quadcopter/rgbd_camera/image_raw/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS
  qos:
    publisher:
      history: keep_last
      history_depth: 1
      reliability: best_effort
      durability: volatile
      deadline:
        sec: 0
        nsec: 100000000  # 10Hz
      lifespan:
        sec: 0
        nsec: 100000000  # 10Hz

- ros_topic_name: "/quadcopter/rgbd_camera/depth/image_raw"
  gz_topic_name: "/quadcopter/rgbd_camera/image_raw/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS
  qos:
    publisher:
      history: keep_last
      history_depth: 1
      reliability: best_effort
      durability: volatile
      deadline:
        sec: 0
        nsec: 100000000  # 10Hz
      lifespan:
        sec: 0
        nsec: 100000000  # 10Hz

- ros_topic_name: "/quadcopter/rgbd_camera/depth/camera_info"
  gz_topic_name: "/quadcopter/rgbd_camera/depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS
  qos:
    publisher:
      history: keep_last
      history_depth: 1
      reliability: best_effort
      durability: volatile
      deadline:
        sec: 0
        nsec: 100000000  # 10Hz
      lifespan:
        sec: 0
        nsec: 100000000  # 10Hz

- ros_topic_name: "/quadcopter/rgbd_camera/points"
  gz_topic_name: "/quadcopter/rgbd_camera/image_raw/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
  qos:
    publisher:
      history: keep_last
      history_depth: 1
      reliability: best_effort
      durability: volatile
      deadline:
        sec: 0
        nsec: 100000000  # 10Hz
      lifespan:
        sec: 0
        nsec: 100000000  # 10Hz
